[build]
  publish = "."

[[redirects]]
  from = "/tableau/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin-qr"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin-editeur"
  to = "/index.html"
  status = 200
