[build]
  publish = "."

[[redirects]]
  from = "/tableau/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chj"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chj/*"
  to = "/index.html"
  status = 200
